// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GachaRepository is an autogenerated mock type for the GachaRepository type
type GachaRepository struct {
	mock.Mock
}

// PostOneUserGacha provides a mock function with given fields: ctx, prizeId, walletId
func (_m *GachaRepository) PostOneUserGacha(ctx context.Context, prizeId int, walletId int) error {
	ret := _m.Called(ctx, prizeId, walletId)

	if len(ret) == 0 {
		panic("no return value specified for PostOneUserGacha")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, prizeId, walletId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGachaRepository creates a new instance of GachaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGachaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GachaRepository {
	mock := &GachaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
