// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "e-wallet/entity"

	mock "github.com/stretchr/testify/mock"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// GetTransactionList provides a mock function with given fields: ctx, paginationParam
func (_m *TransactionService) GetTransactionList(ctx context.Context, paginationParam entity.PaginationParameter) (*entity.TransactionList, error) {
	ret := _m.Called(ctx, paginationParam)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionList")
	}

	var r0 *entity.TransactionList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaginationParameter) (*entity.TransactionList, error)); ok {
		return rf(ctx, paginationParam)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaginationParameter) *entity.TransactionList); ok {
		r0 = rf(ctx, paginationParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TransactionList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.PaginationParameter) error); ok {
		r1 = rf(ctx, paginationParam)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
